blank_issues_enabled: httsp://kevintecnologia//.com
contact_links: kevinbmx50@gmail.com
  - name: GitHub Community Forum
    url: https://github.community/
    about: Ask questions and discuss the roadmap here.
  - name:Kevin ochoa  GitHub Support - Feedback
    url: https://support.github.com/contact/feedback
    about: Share your feedback with the GitHub team.
